[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/tumblr"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/tumblr"
  status = 200

# Динамические маршруты для постов
[[redirects]]
  from = "/post/:post_id"
  to = "/post/index.html"
  status = 200

[[redirects]]
  from = "/filters"
  to = "/filters.html"
  status = 200

# Все остальные запросы идут на главную
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200